const PHASES=['login','navigation','overview','users','audit','ops'];
export class MasterJourney{constructor(){this.controls=new Map();this.checkpoints={};this.masterStatuses=[];this.opsStatuses=[]}
get loginWorkspace(){return this.checkpoints.login?.generate===true}
snapshot(text){this.controls.clear();for(const line of text.split('\n')){const m=line.match(/uid=([\d_]+) (button|link) "([^"]*)"/);if(!m)continue;const[,uid,role,name]=m;const p=name==='관리 콘솔'?'master':name==='운영'?'ops':name==='운영 현황'?'overview':name==='사용자'?'users':name==='Audit'?'audit':null;if(p)this.controls.set(uid,{uid,role,purpose:p,disabled:/(?:^|\s)disabled(?:\s|$)/.test(line)})}return[...this.controls.values()]}
prepare(c){if(c.op==='checkpoint'){if(!PHASES.includes(c.phase)||c.phase!==PHASES[Object.keys(this.checkpoints).length])throw Error('phase');return{phase:c.phase}}if(c.op!=='call'||!['click','navigate_page'].includes(c.name))return null;const a=c.arguments;if(c.name==='navigate_page'){if(a.url==='http://127.0.0.1:18156/login')return null;if(a.url==='http://127.0.0.1:18156/api/auth/google/start?ui=1&return_to=%2Fgenerate')return{args:a,purpose:'auth_fixture'};throw Error('nav')}const x=this.controls.get(a.uid);if(!x||x.disabled)throw Error('fresh');this.controls.clear();return{args:a,purpose:x.purpose}}
async observe(r){const p=new URL(r.url()).pathname;if(p.startsWith('/api/master/'))this.masterStatuses.push(r.status());if(p.startsWith('/api/ops/'))this.opsStatuses.push(r.status())}
async checkpoint(phase,pageId,call){const t=await call('evaluate_script',{pageId,function:`()=>{const text=document.body.innerText;const links=[...document.querySelectorAll('a')].map(x=>x.textContent?.trim());return{generate:location.pathname==='/generate',master:location.pathname==='/master',ops:location.pathname==='/ops',nav:links.includes('관리 콘솔'),overview:text.includes('운영 현황'),users:text.includes('사용자'),audit:text.includes('Audit'),ops_visible:text.includes('운영 상태')}}`});const m=t.match(/```(?:json)?\s*([\s\S]*?)```/);if(!m)throw Error('probe');const p=JSON.parse(m[1]);const ok={login:p.generate,navigation:p.generate&&p.nav,overview:p.master&&p.overview&&this.masterStatuses.includes(200),users:p.master&&p.users&&this.masterStatuses.includes(200),audit:p.master&&p.audit&&this.masterStatuses.includes(200),ops:p.ops&&p.ops_visible&&this.opsStatuses.includes(200)}[phase]===true;if(ok)this.checkpoints[phase]=p;return{phase,passed:ok,...p}}
result(){const phases=Object.fromEntries(PHASES.map(p=>[p,!!this.checkpoints[p]]));return{scenario:'master_workspace',technical_complete:Object.values(phases).every(Boolean),passed:Object.values(phases).every(Boolean),phases,master_statuses:this.masterStatuses,ops_statuses:this.opsStatuses}}
}
