const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const PHASES=['login','mode','incomplete','submitted','completed','reloaded'];
const normalize=s=>s==='pending'?'pending':s==='completed'?'completed':['queued','generating','polling','downloading'].includes(s)?'running':null;
export function pipelineRoute(path){if(path==='/api/pipelines')return path;if(/^\/api\/pipelines\/[0-9a-f-]{36}$/.test(path))return'/api/pipelines/{parent}';return null}
export class PipelineJourney{
 constructor(){this.controls=new Map();this.checkpoints={};this.parentId=null;this.childId=null;this.parentStates=[];this.childStates=['blocked'];this.sameIdentity=false;this.sourceLinked=false;this.reads=0;this.reloadReads=null;this.incompleteAccessibilityDisabled=null;this.failures=[]}
 get loginWorkspace(){return this.checkpoints.login?.workspace===true}
 snapshot(text){this.controls.clear();for(const line of text.split('\n')){const m=line.match(/uid=([\d_]+) (button|textbox) "([^"]*)"/);if(!m)continue;const[,uid,role,name]=m;const purpose=name==='Google로 계속하기'?'login':name==='PIPELINE'?'pipeline_mode':name==='이미지 프롬프트'?'image_prompt':name==='영상 프롬프트'?'video_prompt':name==='Pipeline 생성'?'generate':null;if(purpose)this.controls.set(uid,{uid,role,purpose,disabled:/(?:^|\s)disabled(?:\s|$)/.test(line)})}return[...this.controls.values()]}
 prepare(c){if(c.op==='checkpoint'){const fields=c.phase==='incomplete'?'accessibility_disabled,op,phase':'op,phase';if(!PHASES.includes(c.phase)||Object.keys(c).sort().join(',')!==fields)throw Error('phase_refused');if(c.phase!==PHASES[Object.keys(this.checkpoints).length])throw Error('phase_order');if(c.phase==='incomplete')this.incompleteAccessibilityDisabled=c.accessibility_disabled;return{phase:c.phase}}
  if(c.op!=='call'||!['click','fill','navigate_page'].includes(c.name))return null;const a=c.arguments;if(!a||!Number.isInteger(a.pageId))throw Error('arguments_refused');if(c.name==='navigate_page'){if(a.url==='http://127.0.0.1:18156/login')return null;if(a.type==='reload'&&this.checkpoints.completed){this.reloadReads=this.reads;return{args:a,purpose:'reload'}}throw Error('navigation_refused')}
  const x=this.controls.get(a.uid);if(!x||x.disabled)throw Error('fresh_control_required');if(c.name==='fill'){const value=a.fixture==='empty'&&x.purpose==='video_prompt'&&this.checkpoints.mode?'':a.fixture==='video'&&x.purpose==='video_prompt'&&this.checkpoints.incomplete?'A gentle camera move.':null;if(value===null)throw Error('fixture_refused');this.controls.clear();return{args:{pageId:a.pageId,uid:a.uid,value},purpose:x.purpose}}
  const allowed=x.purpose==='login'||x.purpose==='pipeline_mode'&&this.checkpoints.login||x.purpose==='generate'&&this.checkpoints.incomplete;if(!allowed)throw Error('click_refused');this.controls.clear();return{args:a,purpose:x.purpose}}
 async observe(r){const path=new URL(r.url()).pathname,status=r.status();if(path==='/api/pipelines'&&r.request().method()==='POST'){if(status!==201){this.failures.push('pipeline_http');return}const b=await r.json();if(!UUID.test(b.id)||!UUID.test(b.parent?.id)||!UUID.test(b.child?.id))throw Error('pipeline_invalid');this.parentId=b.parent.id;this.childId=b.child.id;this.sameIdentity=b.id===b.parent.id&&b.child.parent_job_id===b.parent.id}
  else if(this.parentId&&path===`/api/pipelines/${this.parentId}`&&status===200){const b=await r.json();this.reads++;this.sameIdentity=this.sameIdentity&&b.id===this.parentId&&b.parent.id===this.parentId&&b.child.id===this.childId&&b.child.parent_job_id===this.parentId;const ps=normalize(b.parent.state),cs=b.child.blocked?'blocked':normalize(b.child.state);if(ps&&this.parentStates.at(-1)!==ps)this.parentStates.push(ps);if(cs&&this.childStates.at(-1)!==cs)this.childStates.push(cs);const source=b.child.source_asset_id,parentAsset=b.parent.assets?.[0]?.id;this.sourceLinked=!!source&&source===parentAsset}}
 async checkpoint(phase,pageId,call){const t=await call('evaluate_script',{pageId,function:`()=>{const submit=document.querySelector('.creative-composer__actions button[type="submit"]');const fields=[...document.querySelectorAll('.creative-prompt-field textarea')];return{workspace:location.pathname==='/generate',video_empty:fields[1]?.value==='',disabled:!!submit&&submit.disabled,detail:location.pathname.startsWith('/pipelines/'),results:document.querySelectorAll('.pipeline-job').length>=2}}`});const m=t.match(/```(?:json)?\s*([\s\S]*?)```/);if(!m)throw Error('probe');const p=JSON.parse(m[1]);const done=this.parentStates.at(-1)==='completed'&&this.childStates.at(-1)==='completed';const ok={login:p.workspace,mode:p.workspace,incomplete:p.workspace&&p.video_empty,submitted:p.detail,completed:p.detail&&done,reloaded:p.detail&&done&&this.reloadReads!==null&&this.reads>this.reloadReads}[phase]===true;if(ok)this.checkpoints[phase]=p;return{phase,passed:ok,...p}}
 result(){const phases=Object.fromEntries(PHASES.map(p=>[p,!!this.checkpoints[p]]));return{scenario:'pipeline_generation',technical_complete:Object.values(phases).every(Boolean),passed:Object.values(phases).every(Boolean)&&this.incompleteAccessibilityDisabled===true&&this.sameIdentity&&this.sourceLinked&&this.parentStates.at(-1)==='completed'&&this.childStates.at(-1)==='completed',phases,incomplete_accessibility_disabled:this.incompleteAccessibilityDisabled,same_identity:this.sameIdentity,source_linked:this.sourceLinked,parent_states:this.parentStates,child_states:this.childStates,parent_state:this.parentStates.at(-1)??null,child_state:this.childStates.at(-1)??null,reads:this.reads,failures:this.failures}}
}
