const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,PHASES=['login','history','filtered','page2','page1','detail','retry_completed','usage','usage_reloaded'];
export function workspaceRoute(path){if(path==='/api/generations'||path==='/api/usage')return path;if(/^\/api\/generations\/[0-9a-f-]{36}(?:\/retry)?$/.test(path))return path.endsWith('/retry')?'/api/generations/{job}/retry':'/api/generations/{job}';if(path.startsWith('/api/ops/')||path.startsWith('/api/master/'))return path;return null}
export class WorkspaceJourney{constructor(retryJob){if(!UUID.test(retryJob))throw Error('retry_invalid');this.retryJob=retryJob;this.controls=new Map();this.checkpoints={};this.retryId=null;this.retryStates=[];this.historyStatuses=[];this.usageStatuses=[];this.deleteCalls=0;this.reloadUsageReads=null;this.failures=[]}
get loginWorkspace(){return this.checkpoints.login?.workspace===true}
snapshot(text){this.controls.clear();for(const line of text.split('\n')){const m=line.match(/uid=([\d_]+) (button|link|combobox) "([^"]*)"/);if(!m)continue;const[,uid,role,name]=m;let p=/^기록(?:\s+\d+)?$/.test(name)?'history':name==='사용량'?'usage':name==='운영'?'ops':name==='다음'?'next':name==='이전'?'previous':name==='삭제'?'delete':name==='재시도'?'retry':null;if(role==='combobox'&&(name==='상태'||/value="전체 상태"/.test(line)))p='state';if(role==='button'&&name.includes(this.retryJob.slice(0,8)))p='retry_row';if(p)this.controls.set(uid,{uid,role,purpose:p,disabled:/(?:^|\s)disabled(?:\s|$)/.test(line)})}return[...this.controls.values()]}
prepare(c){if(c.op==='checkpoint'){if(!PHASES.includes(c.phase)||Object.keys(c).sort().join(',')!=='op,phase'||c.phase!==PHASES[Object.keys(this.checkpoints).length])throw Error('phase');return{phase:c.phase}}
 if(c.op!=='call'||!['click','fill','navigate_page','handle_dialog'].includes(c.name))return null;const a=c.arguments;if(c.name==='navigate_page'){if(a.url==='http://127.0.0.1:18156/login')return null;if(a.type==='url'&&a.url==='http://127.0.0.1:18156/api/auth/google/start?ui=1&return_to=%2Fgenerate')return{args:a,purpose:'auth_fixture'};if(a.type==='reload'&&this.checkpoints.usage){this.reloadUsageReads=this.usageStatuses.length;return{args:a,purpose:'usage_reload'}}throw Error('nav')}
 if(c.name==='handle_dialog'){if(a.action!=='dismiss'||!this.checkpoints.page1)throw Error('dialog');return{args:a,purpose:'delete_cancel'}}const x=this.controls.get(a.uid);if(!x||x.disabled)throw Error('fresh');if(c.name==='fill'){if(x.purpose!=='state'||a.fixture!=='failed')throw Error('fixture');this.controls.clear();return{args:{pageId:a.pageId,uid:a.uid,value:'실패'},purpose:'state'}}this.controls.clear();return{args:a,purpose:x.purpose}}
async observe(r){const path=new URL(r.url()).pathname,status=r.status(),method=r.request().method();if(path==='/api/generations'&&method==='GET')this.historyStatuses.push(status);else if(path.endsWith('/retry')&&method==='POST'){if(status!==201){this.failures.push('retry_http');return}const b=await r.json();this.retryId=b.id}else if(this.retryId&&path===`/api/generations/${this.retryId}`&&status===200){const b=await r.json();const s=b.state==='pending'?'pending':b.state==='completed'?'completed':['queued','generating','downloading'].includes(b.state)?'running':null;if(s&&this.retryStates.at(-1)!==s)this.retryStates.push(s)}else if(path==='/api/usage')this.usageStatuses.push(status);else if(method==='DELETE')this.deleteCalls++}
async checkpoint(phase,pageId,call){const t=await call('evaluate_script',{pageId,function:`()=>{const rows=document.querySelectorAll('.history-row').length;const metrics=[...document.querySelectorAll('.creative-metric strong')].map(x=>x.textContent?.trim());return{history:location.pathname==='/history',detail:location.pathname.startsWith('/jobs/'),usage:location.pathname==='/usage',rows,page:Number(metrics[2]||0),filters:Number(metrics[1]||0),plan:[...document.querySelectorAll('*')].some(x=>x.textContent?.trim()==='FREE'),retry_visible:!!document.querySelector('.history-retry-button')||[...document.querySelectorAll('button')].some(x=>x.textContent?.trim()==='재시도')}}`});const m=t.match(/```(?:json)?\s*([\s\S]*?)```/);if(!m)throw Error('probe');const p=JSON.parse(m[1]);const ok={login:!p.history&&!p.detail&&!p.usage,history:p.history&&p.rows===10,filtered:p.history&&p.filters===1&&p.rows===10,page2:p.history&&p.page===2&&p.rows===2,page1:p.history&&p.page===1&&p.rows===10,detail:p.detail&&p.retry_visible,retry_completed:p.detail&&this.retryStates.at(-1)==='completed',usage:p.usage&&p.plan,usage_reloaded:p.usage&&p.plan&&this.reloadUsageReads!==null&&this.usageStatuses.length>this.reloadUsageReads}[phase]===true;if(ok)this.checkpoints[phase]=p;return{phase,passed:ok,...p}}
result(){const phases=Object.fromEntries(PHASES.map(p=>[p,!!this.checkpoints[p]]));return{scenario:'workspace_user',technical_complete:Object.values(phases).every(Boolean),passed:Object.values(phases).every(Boolean)&&this.deleteCalls===0,phases,retry_state_path:this.retryStates,history_statuses:this.historyStatuses,usage_statuses:this.usageStatuses,delete_calls:this.deleteCalls,failures:this.failures}}
}
